services:
  postgres:
    image: postgres:13
    container_name: realestate_db
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5433:5432"
    volumes:
      - realestate_db_data:/var/lib/postgresql/data
    restart: always

volumes:
  realestate_db_data:
